services:
  db-user:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    container_name: zetcord_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://user_user:user@db-user:5432/user_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      - db-user
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./secrets:/secrets
      - ./media:/app/media

volumes:
  postgres_user_data:
